### ISSUE TITLE
Unable to shut down app

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/AppStoreClient#1]
When trying to shut down and app from `AppStoreClient` it loads forever. Page refresh required to get back to working state.

Administration log panel contains next entries:
```
"ScErrCodeHostProcessNotExited (SCERR10018): When asked to shut down, the user code process agreed to shut down, but the process didn't exit gracefully in time. Killing it.. (, PID=48780, Database=default)
Version: 2.0.3130.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10018."
```

```
User code process takes longer than expected to exit. (, PID=48780, Database=default)
```

```
"System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.Internal.Web.StaticWebServer.GetFileResource(Response cached, String relativeUri, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3130.3\Level1\src\Starcounter.Hypermedia\StaticWebServer.File.cs:line 90
   at Starcounter.Internal.Web.StaticWebServer.GetStaticResponseClone(String relativeUri, Request request) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3130.3\Level1\src\Starcounter.Hypermedia\StaticWebServer.cs:line 131
   at Starcounter.Internal.Web.AppRestServer.ResolveAndPrepareFile(String relativeUri, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3130.3\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 137
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3130.3\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 112
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3130.3\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 273
HResult=-2147467261
"
```

To reproduce this you have to:
1. Start `AppStoreClient`.
2. Install an app.
3. Run the app.
4. Try to stop the app.

**Comment by miyconst** [comment]
Ping @andwah.

**Comment by andwah** [comment]
@miyconst I could not recreate it in my environment, i will try again with the latest version.

**Comment by miyconst** [comment]
Then I close it, because with the new Administrator I can't reproduce it either.
